// ── SCHOOL HUB PAGES ────────────────────────────────────────────────────
// Powers the "search by school" dropdown in index.html's hero search card.
// Auto-generated by generate-listings.js from live Airtable records (the
// Schools field on each activity) — do not hand-edit here, changes will be
// overwritten on the next run. To add a school, tag an activity with it in
// Airtable and it appears here (and gets its own /schools/{slug} page)
// automatically.
const SCHOOLS = [{"name":"St Oliver Plunkett NS (Malahide)","slug":"st-oliver-plunkett-ns-malahide","url":"https://sortd-ireland.ie/schools/st-oliver-plunkett-ns-malahide"}];
